import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ChevronRight, Download, Menu, Radio, X } from "lucide-react";
import "@/App.css";

const IMG1 = "https://customer-assets-39nsmqrw.emergentagent.net/job_d6240a86-2b93-4548-8523-06b2261c71da/artifacts/5fb260v9_Spider%20man%201.webp";
const HANGING = "https://customer-assets-39nsmqrw.emergentagent.net/job_d6240a86-2b93-4548-8523-06b2261c71da/artifacts/8fa16u5c_Hanging.jpe";
const IMG2 = "https://customer-assets-39nsmqrw.emergentagent.net/job_d6240a86-2b93-4548-8523-06b2261c71da/artifacts/oo4hygsb_Spider%20man%202.webp";

const projects = [
  { id: "001", title: "Government Aadhaar Data Prediction Model", domain: "AI / DATA SCIENCE", year: "2026", status: "SELECTED / FINALIST", stack: "Python · NumPy · Pandas · Scikit-Learn", image: IMG2, text: "Designed a machine learning model to predict patterns in government Aadhaar data, with preprocessing pipelines and a clean HTML visualization interface. Successfully cleared the UIDAI Hackathon 2026 selection round; the final round was age-restricted to 18+." },
  { id: "002", title: "Mobile Privacy & Security Analysis Model", domain: "CYBERSECURITY", year: "2026", status: "CONTROLLED POC", stack: "Linux · Web · Security Research", image: IMG1, text: "A controlled educational proof-of-concept exploring how malicious applications can attempt silent, unauthorized access to photos and videos. The interactive demonstration visualizes background permission and data-harvesting risks without providing operational misuse instructions." }
];
const skills = ["CYBERSECURITY", "AI / ML", "WEB", "PYTHON", "LINUX", "DATA", "UI DESIGN"];
const nav = [["SYSTEM", "system"], ["IDENTITY", "identity"], ["MISSIONS", "missions"], ["ARSENAL", "arsenal"], ["ACHIEVEMENTS", "achievements"], ["MISSION LOG", "log"], ["SECURE CHANNEL", "contact"]];

function App() {
  const [boot, setBoot] = useState(true), [menu, setMenu] = useState(false), [sense, setSense] = useState(false), [sound, setSound] = useState(false), [assistant, setAssistant] = useState(false), [terminal, setTerminal] = useState(false), [selected, setSelected] = useState(null), [query, setQuery] = useState(""), [replies, setReplies] = useState([]), [avatar, setAvatar] = useState({ x: 0, y: 0 });
  const audio = useRef(null);
  const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
  const play = (frequency = 420) => { if (!sound) return; const C = window.AudioContext || window.webkitAudioContext; if (!C) return; audio.current = audio.current || new C(); const osc = audio.current.createOscillator(), gain = audio.current.createGain(); osc.frequency.value = frequency; gain.gain.setValueAtTime(.035, audio.current.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.current.currentTime + .12); osc.connect(gain).connect(audio.current.destination); osc.start(); osc.stop(audio.current.currentTime + .12); };
  const go = (id) => { play(520); setMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  useEffect(() => { const timer = setTimeout(() => setBoot(false), 3600); const key = (e) => { if (e.ctrlKey && e.key.toLowerCase() === "k") { e.preventDefault(); setTerminal(true); } }; window.addEventListener("keydown", key); return () => { clearTimeout(timer); window.removeEventListener("keydown", key); }; }, []);
  useEffect(() => { const move = (e) => { const x = ((e.clientX / window.innerWidth) - .5) * 2, y = ((e.clientY / window.innerHeight) - .5) * 2; setAvatar({ x: x * 12, y: y * 8 }); }; window.addEventListener("pointermove", move); return () => window.removeEventListener("pointermove", move); }, []);
  const answer = (text) => { const q = text.toLowerCase(); let response = q.includes("project") ? "Yash has two documented missions: an Aadhaar data prediction model selected at UIDAI Hackathon 2026, and a controlled mobile privacy/security proof-of-concept." : q.includes("skill") || q.includes("technology") ? "His active arsenal includes cybersecurity, AI/ML, Python, web development, Linux, UI design, NumPy, Pandas, Scikit-Learn, C++ and SQL." : q.includes("contact") || q.includes("email") ? "Secure channel: AKHISWEETY01@GMAIL.COM · YASHRAJ.CONTACTT@GMAIL.COM · +91 9060170251." : "Yash Raj is a Class 12 PCM + Computer Science student from Gaya, Bihar, building hands-on experiments across security, AI and web."; setReplies((r) => [...r, { q: text, response }]); setQuery(""); };
  if (boot) return <div className="boot" data-testid="startup-sequence"><div className="boot-grid" /><div className="boot-copy"><span className="eyebrow">YASH RAJ // PORTFOLIO OS</span><h1>INITIALIZING<br /><em>WEB SYSTEM</em></h1><div className="boot-lines"><p>NEURAL LINK <b>............ ONLINE</b></p><p>HUD CORE <b>.............. ONLINE</b></p><p>MISSION DATABASE <b>...... ONLINE</b></p><p>SECURITY LAYER <b>........ ACTIVE</b></p></div><button className="enter" data-testid="enter-system-button" onClick={() => { play(700); setBoot(false); }}>ENTER SYSTEM <ArrowUpRight size={16} /></button><button className="skip" data-testid="skip-intro-button" onClick={() => setBoot(false)}>SKIP INTRO</button></div><div className="boot-mark">Y / 01</div></div>;
  return <main className={sense ? "app sense-on" : "app"} data-testid="portfolio-app">
    <div className="grain" aria-hidden="true" /><div className="web-lines" aria-hidden="true" /><header className="hud-header"><button className="brand" data-testid="brand-home-button" onClick={() => go("system")}><span className="brand-mark">✳</span><span>YASH RAJ <small>// OS-01</small></span></button><nav className="desktop-nav">{nav.slice(0, 5).map(([label, id]) => <button key={id} data-testid={`nav-${id}-button`} onClick={() => go(id)}>{label}</button>)}</nav><div className="header-actions"><button className="sense-toggle" aria-pressed={sense} data-testid="spider-sense-toggle" onClick={() => { play(630); setSense(!sense); }}><Radio size={13} /> SENSE: {sense ? "ON" : "OFF"}</button><button className="menu-button" data-testid="menu-open-button" onClick={() => { play(480); setMenu(true); }}><Menu size={17} /> MENU</button></div></header>
    <section id="system" className="hero section"><div className="hero-copy reveal"><span className="eyebrow">// CYBERSECURITY / AI / BUILDER</span><h1>YASH<br /><span>RAJ</span></h1><p className="hero-lede">BUILD. SECURE.<br />EXPERIMENT.</p><div className="hero-actions"><button className="primary-button" data-testid="hero-missions-button" onClick={() => go("missions")}>ENTER MISSIONS <ChevronRight size={16} /></button><span className="availability"><i /> STATUS: ACTIVE</span></div></div><div className="hero-frame reveal"><div className="frame-meta"><span>01 / SYSTEM</span><span>GAYA, BIHAR</span></div><img src={IMG1} alt="Cinematic web-slinger moving through a night city" /><div className="frame-title">CYBER<br /><strong>SECURITY</strong></div><div className="reticle reticle-a">+</div><div className="frame-caption"><b>REFLEX</b><span>Turning curiosity into technical experiments.</span></div><div className="frame-caption right"><b>RESOLVE</b><span>Learning by building, testing and solving.</span></div></div><aside className="hero-side telemetry"><span>TELEMETRY / 001</span><strong>CLASS 12</strong><small>PCM + COMPUTER SCIENCE<br />CBSE · 2025—2027</small><div className="telemetry-line" /><span>FOCUS ARRAY</span><small>PYTHON · LINUX<br />MACHINE LEARNING</small></aside></section>
    <section id="identity" className="section split-section"><div className="section-heading"><span className="section-number">02</span><p className="eyebrow">IDENTITY SCAN</p><h2>CURIOUS<br /><em>BY DESIGN.</em></h2></div><div className="identity-panel dossier"><div className="dossier-top"><span>IDENTITY VERIFIED</span><span className="status-dot">● ACTIVE BUILDER</span></div><div className="identity-grid"><div><label>NAME</label><strong>YASH RAJ</strong><label>ROLE</label><strong>CYBERSECURITY ENTHUSIAST</strong><label>LOCATION</label><strong>GAYA, BIHAR</strong></div><div className="identity-text"><p>A motivated Class 12 student studying PCM + Computer Science, building real technical experiments across cybersecurity, AI/ML, Python, Linux and web development.</p><p>Self-taught, hands-on and curious about how systems work — and how to make them better.</p></div></div></div></section>
    <section id="missions" className="section missions"><div className="section-heading row-heading"><div><span className="section-number">03</span><p className="eyebrow">EVIDENCE / FIELD NOTES</p><h2>MISSION<br /><em>DATABASE.</em></h2></div><p className="heading-note">Two documented builds.<br />No inflated metrics.</p></div><div className="mission-grid">{projects.map((project) => <button className="mission-card" data-testid={`mission-${project.id}-card`} key={project.id} onClick={() => { play(360); setSelected(project); }}><div className="mission-image"><img src={project.image} alt="Mission visual" loading="lazy" /><span className="target-lock">TARGET LOCKED ↗</span></div><div className="mission-info"><span className="eyebrow">MISSION {project.id} / {project.year}</span><h3>{project.title}</h3><p>{project.text}</p><div className="mission-footer"><span>{project.domain}</span><span>{project.status}</span></div></div></button>)}</div></section>
    <section id="arsenal" className="section arsenal split-section"><div className="section-heading"><span className="section-number">04</span><p className="eyebrow">CAPABILITY NETWORK</p><h2>THE<br /><em>ARSENAL.</em></h2><p className="section-body">No percentages. Just active learning, working knowledge and hands-on practice.</p></div><div className="skill-network">{skills.map((skill, i) => <button key={skill} data-testid={`skill-${skill.toLowerCase().replaceAll(" ", "-")}-button`} className={`skill-node node-${i}`} onClick={() => setReplies((r) => [...r, { q: skill, response: `${skill} is part of Yash's active learning network.` }])}>{skill}<small>{i < 3 ? "HANDS-ON" : "ACTIVE LEARNING"}</small></button>)}<div className="network-core">Y<br /><span>YASH RAJ</span></div></div></section>
    <section id="achievements" className="section achievements"><div className="section-heading row-heading"><div><span className="section-number">05</span><p className="eyebrow">PROOF OF WORK</p><h2>ACHIEVE<br /><em>MENT.</em></h2></div><div className="level">LEVEL 01 <strong>CURIOUS BUILDER</strong><span><i /></span></div></div><div className="achievement-list"><article><span>01 / 2026</span><h3>UIDAI HACKATHON</h3><p>Selected / finalist-stage achievement for an Aadhaar data prediction model.</p></article><article><span>02 / SECURITY</span><h3>GOOGLE CYBERSECURITY</h3><p>Google Cybersecurity Professional Certificate · Coursera.</p></article><article><span>03 / AI / ML</span><h3>VISHLESAN I-HUB, IIT PATNA</h3><p>Certification in Artificial Intelligence and Machine Learning · 2024—2025.</p></article></div></section>
    <section id="log" className="section log split-section"><div className="section-heading"><span className="section-number">06</span><p className="eyebrow">TIMELINE / JOURNEY</p><h2>MISSION<br /><em>LOG.</em></h2></div><div className="timeline">{[["2024—25", "AI / ML CERTIFICATION", "Vishlesan i-Hub, IIT Patna"], ["2025", "SECONDARY SCHOOL", "CBSE · Scored 89%"], ["2025—27", "CLASS 12", "PCM + Computer Science · In progress"], ["2026", "UIDAI HACKATHON", "Aadhaar data prediction model"]].map(([year, title, desc]) => <div className="timeline-item" key={year}><span>{year}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></section>
    <section id="contact" className="section contact"><div className="contact-copy"><span className="section-number">07</span><p className="eyebrow">OPEN A SECURE CHANNEL</p><h2>LET&apos;S MAKE<br /><em>CONTACT.</em></h2><p>For conversations about learning, building, security or ideas worth testing.</p></div><div className="contact-panel dossier"><span className="eyebrow">TRANSMISSION CONSOLE</span><a data-testid="contact-phone-link" href="tel:+919060170251"><small>PHONE</small><strong>+91 9060170251</strong></a><a data-testid="contact-email-primary-link" href="mailto:akhisweety01@gmail.com"><small>EMAIL / PRIMARY</small><strong>AKHISWEETY01@GMAIL.COM</strong></a><a data-testid="contact-email-secondary-link" href="mailto:yashraj.contactt@gmail.com"><small>EMAIL / SECONDARY</small><strong>YASHRAJ.CONTACTT@GMAIL.COM</strong></a><div className="social-placeholder"><span>GITHUB</span><b>ADD YOUR LINK</b><span>LINKEDIN</span><b>ADD YOUR LINK</b></div></div></section>
    <footer className="footer"><div><span className="eyebrow">SYSTEM STATUS: ONLINE</span><strong>YASH RAJ</strong><small>CYBERSECURITY ENTHUSIAST / AI · SECURITY · WEB</small></div><div className="footer-actions"><button data-testid="web-ai-open-button" onClick={() => setAssistant(true)}>WEB AI <span>↗</span></button><button data-testid="source-download-button" onClick={() => window.open(`${API}/download-source`, "_blank")}><Download size={15} /> SOURCE ZIP</button><button data-testid="sound-toggle-button" onClick={() => setSound(!sound)}>SOUND: {sound ? "ON" : "OFF"}</button></div></footer>
    {menu && <div className="menu-overlay" data-testid="navigation-menu"><button className="menu-close" data-testid="menu-close-button" onClick={() => setMenu(false)}><X /> CLOSE</button><span className="eyebrow">NAVIGATION / WEB ROUTE</span><h2>CHOOSE<br /><em>YOUR THREAD.</em></h2><div className="menu-links">{nav.map(([label, id], i) => <button key={id} data-testid={`overlay-${id}-button`} onClick={() => go(id)}><span>0{i + 1}</span>{label}<ArrowUpRight /></button>)}</div></div>}
    {selected && <div className="modal-backdrop" data-testid="mission-dossier-modal"><article className="mission-modal"><button className="modal-close" data-testid="mission-modal-close-button" onClick={() => setSelected(null)}><X /></button><span className="eyebrow">MISSION {selected.id} / TARGET LOCKED</span><h2>{selected.title}</h2><p>{selected.text}</p><div className="modal-data"><span>DOMAIN <b>{selected.domain}</b></span><span>YEAR <b>{selected.year}</b></span><span>STATUS <b>{selected.status}</b></span><span>TECH STACK <b>{selected.stack}</b></span></div><button className="pending-link" data-testid="mission-link-pending">LINK COMING SOON <ArrowUpRight size={15} /></button></article></div>}
    {assistant && <div className="assistant-panel" data-testid="web-ai-panel"><button className="modal-close" data-testid="web-ai-close-button" onClick={() => setAssistant(false)}><X /></button><span className="eyebrow">WEB AI / STATUS: ONLINE</span><h3>ASK ABOUT<br /><em>YASH&apos;S SYSTEM.</em></h3><div className="assistant-log" aria-live="polite" data-testid="web-ai-response-list">{replies.map((r, i) => <div key={i}><b>YOU / {r.q}</b><p>{r.response}</p></div>)}{!replies.length && <p className="muted">Try: “What projects has Yash built?”</p>}</div><div className="assistant-input"><input data-testid="web-ai-input" value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && query && answer(query)} placeholder="Ask the system..." /><button data-testid="web-ai-submit-button" onClick={() => query && answer(query)}>SEND</button></div></div>}
    {terminal && <div className="terminal" data-testid="terminal-easter-egg"><button data-testid="terminal-close-button" onClick={() => setTerminal(false)}><X /></button><span>YASH@WEB-OS:~$ help</span><p>about · projects · skills · missions · achievements · contact · spider-sense · clear</p><input autoFocus data-testid="terminal-input" placeholder="type a command..." onKeyDown={(e) => { if (e.key === "Enter") { if (e.currentTarget.value === "projects" || e.currentTarget.value === "missions") go("missions"); if (e.currentTarget.value === "spider-sense") setSense(!sense); e.currentTarget.value = ""; } }} /></div>}
  </main>;
}
export default App;
